version: "3"
services:
  libreoffice:
    build: .
    tty: true
    volumes:
      - ./workspace:/workspace:cached
      - ./api:/api:cached
      - ./logs:/var/log:cached
    ports:
      - ${CONVERT_API_PORT}:8000
    environment:
      TZ: "Asia/Tokyo"
      FLASK_APP: run.py
      FLASK_CONFIG: production # development or test or production
      PYTHONPATH: /api/conf:/api/src
    # command: "python run.py"
    command: "uwsgi uwsgi.ini"
    networks:
      - clm-local

networks:
  clm-local:
    external: true
